blank_issues_enabled: false

contact_links:
  - name: ðŸ”’ Security issue or vulnerability
    url: https://whitehub.net/programs/unigetui/
    about: Found a security issue? Please report it via our disclosure program
  - name: ðŸ“§ Contact me privately by email
    url: https://marticliment.com/contact
    about: Please use only if the issue (for example, a vulnerability) cannot be posted publicly
  - name: ðŸ’¬ Having doubts or questions?
    url: https://github.com/marticliment/UniGetUI/discussions/new/choose
    about: Create a discussion and get help from other members of the community
