#name: Auto approve Tolgee PRs

#on: pull_request_target

#jobs:
#  auto-approve:
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write
#    if: contains(github.event.pull_request.labels.*.name, 'tolgee-ci') && github.actor == 'martinet101'
#    steps:
#      - uses: hmarr/auto-approve-action@v4
#        with:
#          review-message: "Tolgee-CI PR has been approved automatically"

