name: Tolgee CI

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Tolgee translations
        env:
          TOLGEE_KEY: "${{ secrets.TOLGEE_TOKEN }}"
        run: |
          cd scripts
          python download_translations.py --autocommit
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          base: main
          token: "${{ secrets.REPO_SCOPED_TOKEN }}"
          labels: tolgee-ci
          title: "Load translations from Tolgee"
          body: ""
          reviewers: "${{ github.repository_owner }}"
          author: "Mart√≠ Climent <marticlilop@gmail.com>"
          commit-message: "Load updated translations from Tolgee"
          branch: pull-request/update-translation
